#!/bin/sh

git --work-tree=/var/www/on/builder_laravel --git-dir=/var/repo/on/builder_laravel checkout -f
chown -R :www-data /var/www/on/builder_laravel
chmod -R 777 /var/www/on/builder_laravel

cd /var/www/on/builder_laravel

composer install --no-dev
php artisan migrate --force
npm i
npm run production

chown -R :www-data /var/www/on/builder_laravel
chmod -R 777 /var/www/on/builder_laravel
